# **-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-**
#|-----------------------------------------|
#              SWAY RETRO THEME
#            Modify by: l3tici4g
#       Inpired by: @jefrecantuledesma
#|-----------------------------------------|
# **-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-**

#: | GRUVBOX Colors

#: Background & Foreground Gradients
    set $bg0H #1d2021
    set $bg0  #282828
    set $bg0S #32302f
    set $bg1  #3c3836
    set $bg2  #504945
    set $bg3  #665c54
    set $bg4  #7c6f64

    set $gray #928374

    set $fg4  #a89984
    set $fg3  #bdae84
    set $fg2  #d5c4a1
    set $fg1  #ebdbb2
    set $fg0  #fbf1c7

#: Neutral Colors
    set $redN    #cc241d
    set $orangeN #d65d0e
    set $yellowN #d79921
    set $greenN  #98971a
    set $aquaN   #689d6a
    set $blueN   #458588
    set $purpleN #b16286
    set $grayN   #a89984

#: Bright Colors
    set $grayB   #928374
    set $purpleB #d3869b
    set $blueB   #83a598
    set $aquaB   #8ec07c
    set $greenB  #b8bb26
    set $yellowB #fabd2f
    set $orangeB #fe8019
    set $redB    #fb4934

#: | Window colors
#   |class                   |border   |background   |text   |indicator   |child_border
    client.focused           $blueN    $blueN        $bg0    $blueN       $blueN
    client.focused_inactive  $bg0H     $bg0H         $fg1    $bg0H        $bg0H
    client.unfocused         $bg0S     $bg0S         $fg1    $bg0S        $bg0S
    client.urgent            $redN     $redN         $bg0H   $redN        $redN
    client.placeholder       $fg0      $fg0          $bg1    $fg0         $fg0
    client.background                  $greenN

#: | Borders
    default_border normal
    default_floating_border normal
    smart_borders on
    smart_gaps off

#: | Cursor Theme
    seat seat0 xcursor_theme Bibata-Modern-Ice 24

#: | Wallpaper
    output * bg /home/leticia/.local/share/backgrounds/rocket.png fill
