# **-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-**
#|-----------------------------------------|
#               SWAY WINDOWS
#            Modify by: l3tici4g
#              Version: 0.0.1
#|-----------------------------------------|
# **-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-**

#: | Variables
#set $mod Mod4
#set $left h
#set $down j
#set $up k
#set $right l

#: | Windows Rules
for_window {
    #: Terminal Emulators
    #[app_id=$id_term] move container to workspace $ws0
    #[app_id=$id_oterm] move container to workspace $ws0

    #: Editors
    [app_id=$id_editor0] workspace_layout tabbed, fullscreen
    [app_id=$id_editor1] workspace_layout tabbed, fullscreen
    [app_id=$id_editor2] workspace_layout tabbed, fullscreen

    #: Browsers
    [app_id=$id_browser] fullscreen
    [app_id=$id_obrowser] fullscreen

}

#: | Key bindings

#: Moving windows around

    #: Move your focus around (vim mode)
    bindsym $mod+$left focus left
    bindsym $mod+$down focus down
    bindsym $mod+$up focus up
    bindsym $mod+$right focus right

    #: Move your focus around (classic mode)
    bindsym $mod+Left focus left
    bindsym $mod+Down focus down
    bindsym $mod+Up focus up
    bindsym $mod+Right focus right

    #: Move the focused window for different layout (vim mode)
    bindsym $mod+Shift+$left move left
    bindsym $mod+Shift+$down move down
    bindsym $mod+Shift+$up move up
    bindsym $mod+Shift+$right move right

    #: Move the focused window for different layout (classic mode)
    bindsym $mod+Shift+Left move left
    bindsym $mod+Shift+Down move down
    bindsym $mod+Shift+Up move up
    bindsym $mod+Shift+Right move right

#: Layout Window

    #: Horizontal & Vertical Splits
    bindsym $mod+b splith
    bindsym $mod+v splitv

    #: Switch the current container between different layout styles
    bindsym $mod+s layout stacking
    bindsym $mod+w layout tabbed
    bindsym $mod+e layout toggle split

    #: Make the current focus fullscreen
    bindsym $mod+Alt+f fullscreen

    #: Toggle the current focus between tiling and floating mode
    bindsym $mod+Shift+space floating toggle

    #: Swap focus between the tiling area and the floating area
    bindsym $mod+space focus mode_toggle

    # Move focus to the parent container
    bindsym $mod+a focus parent
