# **-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-**
#|-----------------------------------------|
#              SWAY WORKSPACES
#            Modify by: l3tici4g
#              Version: 0.0.1
#|-----------------------------------------|
# **-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-**

#: | Variables

set $ws0 1:Terminal
set $ws1 2:Code
set $ws2 3:Search
set $ws3 4:Study
set $ws4 5:Message
set $ws5 6:Music
set $ws6 number 7
set $ws7 number 8
set $ws8 number 9
set $ws9 number 10

#: | Assignments
#: For this session, use 'swaymsg -t get_tree' to get attributes of all open windows.

assign {
    #: Terminal Emulators
    [app_id="kitty"] $ws0
    [app_id="Alacritty"] $ws0

    #: Editors
    [app_id=$id_editor0] $ws1
    [app_id=$id_editor1] $ws1
    [app_id=$id_editor2] $ws1

    #: Browsers
    [app_id="org.mozilla.firefox"] $ws2
    [app_id="app.zen_browser.zen"] $ws2
}

#: | Key bindings

#: Switch to workspace
bindsym $mod+1 workspace $ws0
bindsym $mod+2 workspace $ws1
bindsym $mod+3 workspace $ws2
bindsym $mod+4 workspace $ws3
bindsym $mod+5 workspace $ws4
bindsym $mod+6 workspace $ws5
bindsym $mod+7 workspace $ws6
bindsym $mod+8 workspace $ws7
bindsym $mod+9 workspace $ws8
bindsym $mod+0 workspace $ws9

#: Move to next/previous workspace with active container
bindsym $mod+Tab workspace next
bindsym $mod+Alt+Tab workspace prev

#: Move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws0
bindsym $mod+Shift+2 move container to workspace $ws1
bindsym $mod+Shift+3 move container to workspace $ws2
bindsym $mod+Shift+4 move container to workspace $ws3
bindsym $mod+Shift+5 move container to workspace $ws4
bindsym $mod+Shift+6 move container to workspace $ws5
bindsym $mod+Shift+7 move container to workspace $ws6
bindsym $mod+Shift+8 move container to workspace $ws7
bindsym $mod+Shift+9 move container to workspace $ws8
bindsym $mod+Shift+0 move container to workspace $ws9
